[package]
name = "smalisa"
version = "1.0.0"
authors = ["Danny Rosseau <drosseau@protonmail.com>"]
edition = "2024"

[dependencies]
bitflags = "2.9"
bumpalo = "3.17"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
yoke = { version = "0.8", optional = true, features = ["derive"] }

# Enable features when testing
[dev-dependencies]
smalisa = { path = ".", features = ["serde"] }

[features]
default = ["annotations", "serde"]
# Don't skip over annotations
annotations = []
big-registers = []
serde = ["dep:serde", "bitflags/serde"]
yoke = ["dep:yoke"]
