#[derive(Debug, PartialEq, Eq, Copy, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
pub enum Directive {
    Class,
    Super,
    Implements,
    Source,
    Field,
    EndField,
    Subannotation,
    EndSubannotation,
    Annotation,
    EndAnnotation,
    Enum,
    Method,
    EndMethod,
    Registers,
    Locals,
    ArrayData,
    EndArrayData,
    PackedSwitch,
    EndPackedSwitch,
    SparseSwitch,
    EndSparseSwitch,
    Catch,
    CatchAll,
    Line,
    Param,
    EndParam,
    Local,
    EndLocal,
    RestartLocal,
    Prologue,
    Epilogue,
}
